version: 2

updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Nicholiitus"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Security-first dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    
    ignore:
      # Ignore major version updates that might break compatibility
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    reviewers:
      - "Nicholiitus"
    labels:
      - "github-actions"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker security updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Etc/UTC"
    reviewers:
      - "Nicholiitus"
    labels:
      - "docker"
      - "security"
    commit-message:
      prefix: "docker"
      include: "scope"
